import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import Navbar from "@/components/Navbar";
import { Heading, Box } from "@chakra-ui/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Box maxW="3xl" mx="auto" px="5" mt="5">
          <Heading size='lg' as='i'>Saketh Rajesh</Heading>
          <Navbar />
          {children}
          </Box>
          </Providers>
      </body>
    </html>
  );
}
